---
spring:
  application:
    name: shd-authorization-server
  profiles:
    active:
      - ${PROFILE}

server:
  port: ${SERVER_PORT:8090}
  servlet:
    session:
      timeout: 5m

logging:
  file:
    path: ${LOGGING_FILE_PATH}

shd:
  allowed-origins: ${SHD_ALLOWED_ORIGINS}
  issuer-uri: ${SHD_ISSUER_URI}

# Registered Clients
cms:
  redirect-uri: ${CMS_REDIRECT_URI}
  post-logout-redirect-uri: ${CMS_POST_LOGOUT_REDIRECT_URI}

iprt:
  redirect-uri: ${IPRT_REDIRECT_URI}
  post-logout-redirect-uri: ${IPRT_POST_LOGOUT_REDIRECT_URI}

---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    url: 'jdbc:h2:mem:userdb'

  sql:
    init:
      platform: h2

logging:
  level:
    org:
      springframework:
        security: TRACE
---
spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      platform: ${SPRING_JPA_DATABASE}

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      platform: ${SPRING_JPA_DATABASE}

